repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
