#!/usr/bin/env python
"""
Updates the git commit status
"""
import sys
import os
import argparse
from github import Github
from socket import setdefaulttimeout
from Mu2eCI.logger import log

setdefaulttimeout(120)

parser = argparse.ArgumentParser(
    description="Process a pull request given a repository and PR number."
)
parser.add_argument("--pullrequest", type=int, help="The Pull Request ID.")
parser.add_argument(
    "--repository",
    type=str,
    help="The GitHub repository. Must be in the format e.g. Mu2e/Offline",
)
parser.add_argument(
    "--dry-run",
    type=bool,
    default=False,
    help="Is this a dry run? i.e. don't touch GitHub.",
)
parser.add_argument(
    "--message",
    type=str,
    help="The status message.",
)
parser.add_argument(
    "--test-name",
    type=str,
    help="The test name.",
)
parser.add_argument(
    "--test-name",
    type=str,
    help="The test state.",
    choices=["pending", "failure", "success", "error"],
)
parser.add_argument(
    "--commit",
    type=str,
    help="The test commit.",
)
parser.add_argument(
    "--url",
    type=str,
    help="The git commit status URL.",
)
args = parser.parse_args()

if __name__ == "__main__":
    gh = Github(login_or_token=os.environ["GITHUBTOKEN"], retry=3)
    try:
        repo = gh.get_repo(args.repo)
        pr = repo.get_issue(args.pullrequest)
        repo.get_commit(sha=args.commit).create_status(
            state=args.test_state,
            target_url=args.url,
            description=args.message,
            context=args.test_name,
        )
    except Exception:
        log.exception("Failed to change git commit status: ")
        sys.exit(1)
